rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 1
    - never
  strict:
    - 2
    - function
env:
  es6: true
  browser: true
ecmaFeatures:
  modules: true
extends: 'angular'
